language : c++
dist: bionic

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9

before_install:
    - pip install --user cpp-coveralls

install:
    - wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
    - tar xf boost_1_72_0.tar.gz
    - cd boost_1_72_0
    - ./bootstrap.sh
    - sudo ./b2 -d0 --with-program_options install
    - cd -
    - git clone --depth=1 --single-branch https://github.com/google/googletest.git
    - cd googletest
    - mkdir build
    - cd build
    - cmake .. 
    - sudo make -j`nproc` install
    - cd ../../

script :
    - mkdir build
    - cd build
    - cmake .. -DCOVERAGE=True
    - make -j`nproc`
    - ./test/mawk_test
    - cd -

after_success:
    - coveralls --gcov-options '\-lp'
