language : c++

addons:
    apt:
        update: true
        sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - boost1.67
script :
    - cd src/
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
